name: gen_i18n
description: Library to help you add internationalization in your project dart generating classes and translation files.
version: 1.0.0
homepage: https://github.com/EdvaldoMartins/gen_i18n

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  path: ^1.8.0
  ansicolor: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
